# Generated by Django 3.2.9 on 2021-12-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(default='How to learn english by 24 days', unique=True),
        ),
    ]
